### ISSUE TITLE
How to interpret the visualization?

### ISSUE THREAD

**Issue by vanangamudi** [arogozhnikov/3d_nn#3]
First of all appreciate the effort. I cannot understand the visualization. Can you shine some light on that?

**Comment by arogozhnikov** [comment]
@vanangamudi 

Visualization is just level surfaces (you can stop animation if this is confusing).

Maybe this will help to understand level surfaces: http://calculus7.com/sitebuildercontent/sitebuilderfiles/lvlsurf3.pdf

**Comment by vanangamudi** [comment]
Thanks. That helps
